### ISSUE TITLE
Question editing savefiles

### ISSUE THREAD

**Issue by AWH2332** [Bentheck/Palworld-Server-Setting-Editor#3]
Hello good morning, I have a problem, I started a game with a friend in cooperative mode, he no longer plays and has passed me the files related to the map, server, progress, I have imported it correctly but every time I start the server I start with my friend's character, how can I edit the files to continue the game with my character, my pals and constructions appear on the server but I can not use them.

**Comment by Bentheck** [comment]
I'm sorry, I have no idea how to help you out on this one. I don't think it's even possible to do what you want to do with a cooperative game transfered to a dedicated server.
